### ISSUE TITLE
安装后打不开微信

### ISSUE THREAD

**Issue by Ma-k-w** [MustangYM/WeChatSeptet-ForMac#13]
![image](https://user-images.githubusercontent.com/42510721/91836118-ec226b80-ec7c-11ea-940c-6387dd87d74e.png)
mac os：10.15.2
wechat：2.4.2

都有重新安装过。
卸载小助手后，就能打开微信了。

**Comment by MustangYM** [comment]
把小助手卸载完后，再安装就好了
