### ISSUE TITLE
安装命令有误

### ISSUE THREAD

**Issue by guojunliu** [MustangYM/WeChatSeptet-ForMac#16]
文档中安装命令为
sudo rm -r -f WeChatSeptet-ForMac && git clone https://github.com/MustangYM/WeChatShelby-ForMac && cd WeChatSeptet-ForMac/WeChatSeptet && ./install.sh

实际目录为  WeChatShelby-ForMac

正确的安装命令应该是
sudo rm -r -f WeChatSeptet-ForMac && git clone https://github.com/MustangYM/WeChatShelby-ForMac && cd WeChatShelby-ForMac/WeChatSeptet && ./install.sh

**Comment by guojunliu** [comment]
![image](https://user-images.githubusercontent.com/6713422/93587313-4a20b400-f9dc-11ea-9de9-4dae8f2a0edf.png)

**Comment by MustangYM** [comment]
对不起，马上改
