### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by paysenyu** [MustangYM/WeChatSeptet-ForMac#2]
手动下载简版小助手 
install.sh 拖到终端后提示
cp: ./Rely/WeChatSeptet.framework: No such file or directory

然而实际 /Rely/WeChatSeptet.framework 都是存在的

并且教程中 install 是在/Rely 下，实际是在WeChatSeptet中，尝试过移动依旧无效

**Comment by MustangYM** [comment]
cd到WeChatSpetet文件夹即可
