### ISSUE TITLE
升级Version. 2.6.1 (16871)微信之后，插件消失！

### ISSUE THREAD

**Issue by jhonnymoree** [MustangYM/WeChatSeptet-ForMac#28]
不知道这个版本的微信做了什么操作，升级之后小助手功能失效，然后打算卸载重装来着，但是提示未安装（本人未卸载）！！！！！
尝试重新安装小助手，微信就会崩溃，再次卸载助手之后，微信可正常使用。

**Comment by MustangYM** [comment]
傻逼。
