### ISSUE TITLE
如何定制主题呢？

### ISSUE THREAD

**Issue by shengxinjing** [MustangYM/WeChatSeptet-ForMac#4]
比如换颜色，换icon等

**Comment by MustangYM** [comment]
@shengxinjing 可以在源码中的这里进行颜色的修改[颜色](https://github.com/MustangYM/WeChatSeptet-ForMac/blob/master/WeChatSeptet/WeChatSeptet/PrefixHeader.pch), icon的话就相对麻烦些,需要慢慢调试每个你想替换的地方.

**Comment by shengxinjing** [comment]
非常感谢
